//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthorama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public int appointmentID { get; set; }
        public System.DateTime appointmentTime { get; set; }
        public string patientAppointmentAMKA { get; set; }
        public string doctorAppointmentAMKA { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
