//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthorama.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DOCTOR_AVAILABILITY
    {
        public int ID { get; set; }

        [DisplayName("AMKA")]
        public string doctorAMKA { get; set; }

        [DisplayName("Start")]
        public System.DateTime availabilityStart { get; set; }

        [DisplayName("End")]
        public System.DateTime availabilityEnd { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
    }
}
