//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthorama.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
            this.DOCTOR_AVAILABILITY = new HashSet<DOCTOR_AVAILABILITY>();
        }

        [DisplayName("AMKA")]
        public string doctorAMKA { get; set; }

        [DisplayName("Name")]
        public string doctorName { get; set; }

        [DisplayName("Surname")]
        public string doctorSurname { get; set; }

        [DisplayName("Username")]
        public string doctorUsername { get; set; }

        [DisplayName("Specialty")]
        public string doctorSpeciality { get; set; }

        [DisplayName("Password")]
        public string doctorPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR_AVAILABILITY> DOCTOR_AVAILABILITY { get; set; }
    }
}
