//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthorama.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.APPOINTMENT = new HashSet<APPOINTMENT>();
        }

        [DisplayName("AMKA")]
        public string patientAMKA { get; set; }
        public int patientID { get; set; }

        [DisplayName("Name")]
        public string patientName { get; set; }

        [DisplayName("Surname")]
        public string patientSurname { get; set; }

        [DisplayName("Password")]
        public string patientPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENT { get; set; }
    }
}
